/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.bee.webserver;

import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;

class bound_coords
{
    public String coord_id;
    //geography geog;
    public String event_id;
    public int ordinal;
};

public class BeeWebserver {
	public static void main(String[] args) throws Exception {

        Connection connection = getConnection();

        if(connection != null)
        {
            System.out.println("connection success");
        }
        else
        {
            System.out.println("connection fail");
        }
        
        disconnect(connection);
    }

    private static Connection getConnection() throws URISyntaxException, SQLException {
        URI dbUri = new URI(System.getenv("DATABASE_URL"));

        String username = dbUri.getUserInfo().split(":")[0];
        String password = dbUri.getUserInfo().split(":")[1];
        String dbUrl = "jdbc:postgresql://" + dbUri.getHost() + dbUri.getPath();

        return DriverManager.getConnection(dbUrl, username, password);
    }

    private static void disconnect(Connection conn) throws URISyntaxException, SQLException {
        if(conn !=null){
            try {
                conn.close();
            } catch (SQLException e) {System.out.println("disconnect - Something went wrong.");}
        }
    }

    private static void insertBound_coords(Connection conn, bound_coords b) throws URISyntaxException, SQLException {
      /* String SQL = "INSERT INTO bound_coords(coord_id, event_id) " + "VALUES(?,?,?,?)"; //missing ordinal, geog type

       long id = 0;

       if(conn != null){
           PreparedStatement pstmt = conn.prepareStatement(SQL,Statement.RETURN_GENERATED_KEYS());
            pstmt.setString(1, b.coord_id);
            //pstmt.setString(2, b.geog);
            pstmt.setString(2, b.event_id);
            // pstmt.setString(3, b.ordinal);

            int affectedRows = pstmt.executeUpdate();

            if(affectedRows > 0){
               try (ResultSet rs = pstmt.getGeneratedKeys()){
                    if (rs.next()) {
                       id = rs.getLong(1);
                      }
                } catch (SQLException ex){
                   System.out.println(ex.getMessage());
                }
            }
        } 
       
       return id;
    }*/
       
       
       
       
       
       
         if(conn != null){
            try{
                Statement statement = conn.createStatement();
                statement.executeUpdate("INSERT INTO bound_coords VALUES (b.coord_id, b.geog, b.event_id, b.ordinal)");

            } catch (SQLException e) {System.out.println("addPoint - something went wrong.");}
        }
    }

    

    /*private static void deletePoint(Connection conn, bound_coords b, index i) throws URISyntaxException, SQLException {
        if(conn != null){
            try{
                Statement statement = conn.createStatement();
                statement.executeUpdate("")
            }
        }
    }*/
}
