/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bee.webserver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;


public class BeeWebserver {
	public static void main(String[] args) {
        System.out.println("Test");
        

        Connection conn = null;
        try{
            String dbUrl = System.getenv("JBDC_DATABASE_URL");
            conn = DriverManager.getConnection(dbUrl);
        } catch (SQLException e) {
            throw new Error("Problem", e);
        } finally {
          try {
            if (conn != null) {
                conn.close();
            }
          } catch (SQLException ex) {
              System.out.println(ex.getMessage());
          }
        }
    }
}
