/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bee.webserver;

public class BeeWebserver {
	public static void main(String[] args) {
        System.out.println("Test");
    }
	
}
