/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bee.webserver;

public class BeeWebserverTest {
	/* for testing if things go correctly
    @Test public void testSomeLibraryMethod() {
        BeeWebserver classUnderTest = new BeeWebserver();
    }
    */
}
